### ISSUE TITLE
Failed to add edge detection - Hardware failure?

### ISSUE THREAD

**Issue by Crash0v3r1de** [NebraLtd/helium-rak#25]
Just noticed one of my miners went offline a few weeks ago and the only errors in the log I'm seeing are GPIO related. Wondering if anyone can verify if the concentrator just died or maybe something else?

> <gateway-config> libmraa[13]: libmraa version v2.1.0-24-gbd91964 initialised by user 'root' with EUID 0
> 
> 
> <gateway-config> libmraa[13]: gpio: platform doesn't support chardev, falling back to sysfs
> 
> 
> <gateway-config> libmraa[13]: libmraa initialised for platform 'Raspberry Pi Model B Rev 1' of type 5
> 
> 
> <gateway-config> 2024-02-28 01:08:40,541 - [DEBUG] - __main__ - (__main__.py).validate_env -- /opt/venv/lib/python3.9/site-packages/gatewayconfig/__main__.py:(34) - Starting with the following ENV:
> 
> <gateway-config>         SENTRY_DSN=None
> 
> <gateway-config>         BALENA_APP_NAME=xxxx-xxxx
> 
> <gateway-config>         BALENA_DEVICE_UUID=3395aac54ec624a9535e759c6a61xxxx
> 
> <gateway-config>         VARIANT=COMP-RAKHM
> 
> <gateway-config>         ETH0_MAC_ADDRESS_FILEPATH=/sys/class/net/eth0/address
> 
> <gateway-config>         WLAN0_MAC_ADDRESS_FILEPATH=/sys/class/net/wlan0/address
> 
> <gateway-config>         DIAGNOSTICS_JSON_URL=http://diagnostics/json
> 
> <gateway-config>         ETHERNET_IS_ONLINE_FILEPATH=/sys/class/net/eth0/carrier
> 
> <gateway-config>         FIRMWARE_VERSION=v1.3.0
> 
> <gateway-config> 
> 
> <gateway-config> Traceback (most recent call last):
> 
> <gateway-config>   File "/usr/lib/python3.9/runpy.py", line 197, in _run_module_as_main
> 
> <gateway-config>     return _run_code(code, main_globals, None,
> 
> <gateway-config>   File "/usr/lib/python3.9/runpy.py", line 87, in _run_code
> 
> <gateway-config>     exec(code, run_globals)
> 
> <gateway-config>   File "/opt/venv/lib/python3.9/site-packages/gatewayconfig/__main__.py", line 77, in <module>
> 
> <gateway-config>     main()
> 
> <gateway-config>   File "/opt/venv/lib/python3.9/site-packages/gatewayconfig/__main__.py", line 30, in main
> 
> <gateway-config>     start()
> 
> <gateway-config>   File "/opt/venv/lib/python3.9/site-packages/gatewayconfig/__main__.py", line 57, in start
> 
> <gateway-config>     config_app = GatewayconfigApp(
> 
> <gateway-config>   File "/opt/venv/lib/python3.9/site-packages/gatewayconfig/gatewayconfig_app.py", line 46, in __init__
> 
> <gateway-config>     self.init_gpio(variant)
> 
> <gateway-config>   File "/opt/venv/lib/python3.9/site-packages/gatewayconfig/gatewayconfig_app.py", line 139, in init_gpio
> 
> <gateway-config>     self.user_button = Button(btn, hold_time=USER_BUTTON_HOLD_SECONDS)
> 
> <gateway-config>   File "/opt/venv/lib/python3.9/site-packages/gpiozero/devices.py", line 108, in __call__
> 
> <gateway-config>     self = super(GPIOMeta, cls).__call__(*args, **kwargs)
> 
> <gateway-config>   File "/opt/venv/lib/python3.9/site-packages/gpiozero/input_devices.py", line 414, in __init__
> 
> <gateway-config>     super(Button, self).__init__(
> 
> <gateway-config>   File "/opt/venv/lib/python3.9/site-packages/gpiozero/mixins.py", line 433, in __init__
> 
> <gateway-config>     super(HoldMixin, self).__init__(*args, **kwargs)
> 
> <gateway-config>   File "/opt/venv/lib/python3.9/site-packages/gpiozero/input_devices.py", line 171, in __init__
> 
> <gateway-config>     self.pin.when_changed = self._pin_changed
> 
> <gateway-config>   File "/opt/venv/lib/python3.9/site-packages/gpiozero/pins/__init__.py", line 432, in <lambda>
> 
> <gateway-config>     lambda self, value: self._set_when_changed(value),
> 
> <gateway-config>   File "/opt/venv/lib/python3.9/site-packages/gpiozero/pins/pi.py", line 319, in _set_when_changed
> 
> <gateway-config>     self._enable_event_detect()
> 
> <gateway-config>   File "/opt/venv/lib/python3.9/site-packages/gpiozero/pins/rpigpio.py", line 226, in _enable_event_detect
> 
> <gateway-config>     GPIO.add_event_detect(
> 
> <gateway-config> RuntimeError: Failed to add edge detection

Packet forwarder shows the correct concentrator.

> <packet-forwarder> ##### 2024-02-28 01:08:49 GMT #####
> <packet-forwarder> ### [UPSTREAM] ###
> <packet-forwarder> # RF packets received by concentrator: 0
> <packet-forwarder> # CRC_OK: 0.00%, CRC_FAIL: 0.00%, NO_CRC: 0.00%
> <packet-forwarder> # RF packets forwarded: 0 (0 bytes)
> <packet-forwarder> # PUSH_DATA datagrams sent: 1 (162 bytes)
> <packet-forwarder> # PUSH_DATA acknowledged: 100.00%
> <packet-forwarder> ### [DOWNSTREAM] ###
> <packet-forwarder> # PULL_DATA sent: 3 (100.00% acknowledged)
> <packet-forwarder> # PULL_RESP(onse) datagrams received: 0 (0 bytes)
> <packet-forwarder> # RF packets sent to concentrator: 0 (0 bytes)
> <packet-forwarder> # TX errors: 0
> <packet-forwarder> ### SX1302 Status ###
> <packet-forwarder> # SX1302 counter (INST): 60756175
> <packet-forwarder> # SX1302 counter (PPS):  0
> <packet-forwarder> # BEACON queued: 0
> <packet-forwarder> # BEACON sent so far: 0
> <packet-forwarder> # BEACON rejected: 0
> <packet-forwarder> ### [JIT] ###
> <packet-forwarder> src/jitqueue.c:440:jit_print_queue(): INFO: [jit] queue is empty
> <packet-forwarder> #--------
> <packet-forwarder> src/jitqueue.c:440:jit_print_queue(): INFO: [jit] queue is empty
> <packet-forwarder> ### [GPS] ###
> <packet-forwarder> # GPS *FAKE* coordinates: latitude 0.00000, longitude 0.00000, altitude 0 m
> <packet-forwarder> ##### END #####

On the dashboard it shows radio is operational and ECC is is valid/detected.
Region is set correctly as well as variant.

Not really sure what else to check/verify.

**Comment by Crash0v3r1de** [comment]
The only new findings is the working hotspot (all latest firmware) shows n/a for frequency and the broken one shows US915. I am in the US so not sure why that wouldn't also work.
