### ISSUE TITLE
Fresh Flash - Packet Forwarder Failure

### ISSUE THREAD

**Issue by Crash0v3r1de** [NebraLtd/helium-rak#5]
I don't really know what I can send you but I just flashed the balena helium rak firmware from you guys onto this SD and everything looks solid with the excepton of packet forwarder alling on it's face.

Not sure if this is expected for initial boot up (literally 30 minutes power up time).

Error that keeps looping:
`Traceback (most recent call last):
 packet-forwarder    File "/usr/local/lib/python3.10/runpy.py", line 196, in _run_module_as_main
 packet-forwarder      return _run_code(code, main_globals, None,
 packet-forwarder    File "/usr/local/lib/python3.10/runpy.py", line 86, in _run_code
 packet-forwarder      exec(code, run_globals)
 packet-forwarder    File "/opt/pktfwd/__main__.py", line 13, in <module>
 packet-forwarder      VARIANT = os.environ['VARIANT']
 packet-forwarder    File "/usr/local/lib/python3.10/os.py", line 679, in __getitem__
 packet-forwarder      raise KeyError(key) from None
 packet-forwarder  KeyError: 'VARIANT'`

I don't mind making modifications to the file system however I don't know anything about this python script trying to execute.

**Comment by Crash0v3r1de** [comment]
Ah, set the VARIANT variable and it fixed the forwarder issue. Found that workaround here: https://githublab.com/repository/issues/NebraLtd/helium-miner-software/396

**Comment by Crash0v3r1de** [comment]
closed, but new issues so closing this to make new issue
